### ISSUE TITLE
Type Mismatch

### ISSUE THREAD

**Issue by ngoquanghuy99** [xuxingya/tf2crf#21]
I followed the instruction, even i tried with your example but i still got the same error (i used Colab):
TypeError: Input 'y' of 'AddV2' Op has type float32 that does not match type float16 of argument 'x'.

**Comment by xuxingya** [comment]
There is  a mixed precision training test in tests, can you run it?
And have you change the file tensorflow-addons/text/crf.py according to readme?

**Comment by ngoquanghuy99** [comment]
> There is a mixed precision training test in tests, can you run it?
> And have you change the file tensorflow-addons/text/crf.py according to readme?

I did all the things. Could you try it for once? (Colab) 
Thanks anyway!

**Comment by xuxingya** [comment]
![image](https://user-images.githubusercontent.com/13343428/99472995-aecca080-2984-11eb-9a3c-eca24201f55b.png)
is the error like this?
This is because current tensorflow-addons/crf calculate doesn't support mixed precison. So I mention in readme that ypu need to change a line in that file.

> Currently these is a bug in tensorflow-addons.text.crf, which causes a dtype error when using miex precision. To correctly use mixed precison, you need to modify the line 488 of tensorflow_addons/text/crf.py to:
crf_fwd_cell = CrfDecodeForwardRnnCell(transition_params, dtype=inputs.dtype)

The file path in Colab is :  '/usr/local/lib/python3.6/dist-packages/tensorflow_addons/text/crf.py'
Or you can `pip install -U tfa-nightly` to use the nightly version, but I don't recommend this because it does a forced type transferation and may cause some problems.

**Comment by ngoquanghuy99** [comment]
I changed that line, still got this error (don't know whether i changed in correct way).
Anyways, i solved my problem by another approach. Thanks so much!
