### ISSUE TITLE
ValueError: Shape must be rank 2 but is rank 3

### ISSUE THREAD

**Issue by kakatrina** [xuxingya/tf2crf#27]
Hi, 
Thanks for answering my question here!
I'm building a two layered Bi-lstm with CRF for NER model, but I got the issues like this: 
![image](https://user-images.githubusercontent.com/60328340/102923158-437f5e00-445d-11eb-9a9d-ad4b467302d3.png)
I'm not sure what is going on here. Hopefully, you can point it out to me. Thanks!

**Comment by GuoyiLi1991** [comment]
Hi, 

I actually got the same issue here. I used to use 

from keras_contrib.layers import CRF

but it was not there for tensorflow 2.x. Thank you so much for uploading you code. But I noticed that: if I have a dense layer with dimension of (None, 100, 20), then I pass this layer into the crf.  In this case, I would get a crf layer with a dimension of ((None, 100), (None, 100, 20)). And it will return the same issue as above. Because in the previous CRF function in keras_contrib, there is an attribute we need to assign with the number of tags and it's not here... which makes me even more confused...

max_len = 100
input_layer = Input(shape=(max_len,))
embedded_layer = Embedding(input_dim=5000 + 1, output_dim=20, input_length=max_len, mask_zero=True)(input_layer)
LSTM_layer = Bidirectional(LSTM(units=50, return_sequences=True, recurrent_dropout=0.1))(embedded_layer)
dense_layer = TimeDistributed(Dense(20, activation="relu"))(LSTM_layer)
crf = CRF(dtype='float32')
dense_layer = crf(dense_layer)
base_model = Model(input_layer, dense_layer)
final_model = ModelWithCRFLoss(base_model)

Please advise us how to solve it...

Thanks,
Guoyi

**Comment by xuxingya** [comment]
You can add a dense layer before the crf layer, whose dimension is the number of tag.  This is the same with the keras contrib when setting use_kernel to false. -------- 原始邮件 --------发件人： guoyi <notifications@github.com>日期： 2020年12月29日周二 清晨5:35收件人： xuxingya/tf2crf <tf2crf@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [xuxingya/tf2crf] ValueError: Shape must be rank 2 but is rank 3 (#27)
Hi,
I actually got the same issue here. I used to use
from keras_contrib.layers import CRF
but it was not there for tensorflow 2.x. Thank you so much for uploading you code. But I noticed that: if I have a dense layer with dimension of (None, 100, 20), then I pass this layer into the crf.  In this case, I would get a crf layer with a dimension of ((None, 100), (None, 100, 20)). And it will return the same issue as above. Because in the previous CRF function in keras_contrib, there is an attribute we need to assign with the number of tags and it's not here... which makes me even more confused...
max_len = 100
input_layer = Input(shape=(max_len,))
embedded_layer = Embedding(input_dim=5000 + 1, output_dim=20, input_length=max_len, mask_zero=True)(input_layer)
LSTM_layer = Bidirectional(LSTM(units=50, return_sequences=True, recurrent_dropout=0.1))(embedded_layer)
dense_layer = TimeDistributed(Dense(20, activation="relu"))(LSTM_layer)
crf = CRF(dtype='float32')
dense_layer = crf(dense_layer)
base_model = Model(input_layer, dense_layer)
final_model = ModelWithCRFLoss(base_model)
Please advise us how to solve it...
Thanks,
Guoyi

**Comment by GuoyiLi1991** [comment]
> You can add a dense layer before the crf layer, whose dimension is the number of tag.  This is the same with the keras contrib when setting use_kernel to false. -------- 原始邮件 --------发件人： guoyi <notifications@github.com>日期： 2020年12月29日周二 清晨5:35收件人： xuxingya/tf2crf <tf2crf@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： Re: [xuxingya/tf2crf] ValueError: Shape must be rank 2 but is rank 3 (#27) Hi, I actually got the same issue here. I used to use from keras_contrib.layers import CRF but it was not there for tensorflow 2.x. Thank you so much for uploading you code. But I noticed that: if I have a dense layer with dimension of (None, 100, 20), then I pass this layer into the crf. In this case, I would get a crf layer with a dimension of ((None, 100), (None, 100, 20)). And it will return the same issue as above. Because in the previous CRF function in keras_contrib, there is an attribute we need to assign with the number of tags and it's not here... which makes me even more confused... max_len = 100 input_layer = Input(shape=(max_len,)) embedded_layer = Embedding(input_dim=5000 + 1, output_dim=20, input_length=max_len, mask_zero=True)(input_layer) LSTM_layer = Bidirectional(LSTM(units=50, return_sequences=True, recurrent_dropout=0.1))(embedded_layer) dense_layer = TimeDistributed(Dense(20, activation="relu"))(LSTM_layer) crf = CRF(dtype='float32') dense_layer = crf(dense_layer) base_model = Model(input_layer, dense_layer) final_model = ModelWithCRFLoss(base_model) Please advise us how to solve it... Thanks, Guoyi —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply!

But I still have not resolved this issue. The problem is, when I pass a layer with dimension of (none, 75, 17), which is my desired output format, I will get a wired dimension which seems like ((none, 75), (none, 75, 17)). Please see the code and model summary below.

```
input_layer = Input(shape=(max_len,))
embedded_layer = Embedding(input_dim=n_words + 1, output_dim=20,
                  input_length=max_len, mask_zero=True)(input_layer)  # 20-dim embedding
LSTM_layer = Bidirectional(LSTM(units=50, return_sequences=True,
                           recurrent_dropout=0.0))(embedded_layer)  # variational biLSTM
dense_layer = TimeDistributed(Dense(n_tags, activation="softmax"))(LSTM_layer)  # a dense layer as suggested by neuralNer
crf = CRF(dtype='float32')
out_layer = crf(dense_layer)
base_model = Model(input_layer, out_layer)
final_model = ModelWithCRFLoss(base_model)

base_model.compile(optimizer="adam", loss="categorical_crossentropy", metrics="accuracy")
base_model.summary()
```

![image](https://user-images.githubusercontent.com/29215691/103369148-5f0aea00-4a97-11eb-9126-d1c92a97c829.png)

**Comment by xuxingya** [comment]
Accurately there are four outputs. You can refer to the description of the
CRF layer. They are viterbi_sequence, inputs(the output of the previous
layer), sequence_lengths (mask), self.transitions (crf transmission
parameters). Usually you only need the first one. Sometimes you may want to
custom your own loss or accuracy, then other outputs are needed.

**Comment by Pol-Zeimet** [comment]
> Hi,
> Thanks for answering my question here!
> I'm building a two layered Bi-lstm with CRF for NER model, but I got the issues like this:
> ![image](https://user-images.githubusercontent.com/60328340/102923158-437f5e00-445d-11eb-9a9d-ad4b467302d3.png)
> I'm not sure what is going on here. Hopefully, you can point it out to me. Thanks!

I ran into the same issue today. The solution might be very easy. 
Do you happen to  one hot encode your targets for training? Because you don't need to!
Simply have your target be a list of int. 

I hope that solves your issue.
~Pol

**Comment by RH1994R** [comment]
So anyone found a solution for it? Still struggling with the same problem

**Comment by xuxingya** [comment]
> So anyone found a solution for it? Still struggling with the same problem

Check your input and y. The input to CRF layer should be (batch_size, sequence_len, tags_num), And the y true label should be (batch_size, sequence_len).

**Comment by RH1994R** [comment]
Thanks for your fast answer! My input should be fine, it is (BatchSize, 100, 3). 100 is the max_seq_length and 3 the tags. But my y are shaped in the same way (and one hot encoded). I have got almost the same model as user @GuoyiLi1991 with the same error message. There are 4 output tensors from the crf layer and I would say I need the second tensor by looking at it. How can I get the right tensor out of those 4?

**Comment by Pol-Zeimet** [comment]
> But my y are shaped in the same way (and one hot encoded)

That is your problem right there.
You dont want to one-hot encode your labels.
It changes your shape for labels from (batchsize, sequence length) to (batchsize, sequence length, num_classes)
One-hot encoding your labels results in the shape mismatch in your error (ValueError: shape must be rank 2 but is rank 3)

**Comment by RH1994R** [comment]
Thank you, it finally worked! Unfortunately the f1-score got a lot worse, it was about 61% without CRF, with CRF it is only 57%. Does anyone have an idea why?

**Comment by xuxingya** [comment]
Isn't the model overfitting?

**Comment by RH1994R** [comment]
Why do you think the model is overfitting? Do you have any suggestions to avoid it? In my model I also included a dropout layer.

**Comment by xuxingya** [comment]
Do you calculate the F1 score on the test set? Because the F1 score is quite low, and usually CRF is helpful to NER task, I think there may other problem in your task.

**Comment by RH1994R** [comment]
Yes, I am calculating the F1 score on the test set. My data is labeled really bad, so that's why it is so low in generel. Maybe there is another problem I don't really see now.
But I would really like to thank you for your help! At least I made it work somehow
